language: java
python:
  - "2.7"
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - wget
      - mercurial

# Use Trusty to get enough RAM
sudo: required
dist: trusty

jdk:
    - oraclejdk11

env:
  global:
    - JVMCI_VERSION="jvmci-0.46"
    - JDK8_UPDATE_VERSION="172"
  matrix:
    - JDK="jdk8" GATE="style,fullbuild"
    - JDK="jdk8" GATE="build,test"
    - JDK="jdk8" GATE="build,bootstraplite"
    - JDK="jdk11" GATE="style,fullbuild"
    - JDK="jdk11" GATE="build,test"
    - JDK="jdk11" GATE="build,bootstraplite"
install:
  - |
      export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
      git clone https://github.com/graalvm/mx.git ${MX_PATH}
      export PATH=${PATH}:${MX_PATH}
  - |
      if [[ ${GATE} == *style* ]]
      then
        virtualenv venv
        source venv/bin/activate
        pip install astroid==1.1.0
        pip install pylint==1.1.0

        export ECLIPSE_TAR=${TRAVIS_BUILD_DIR}/../eclipse.tar.gz
        wget http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz -O ${ECLIPSE_TAR}
        tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${ECLIPSE_TAR}
        export ECLIPSE_EXE=${TRAVIS_BUILD_DIR}/../eclipse/eclipse
      fi
  - |
      if [[ ${GATE} == *fullbuild* ]]
      then
        # Only test JDT on JDK8
        if [ "${JDK}" == "jdk8" ]
        then
          export JDT=${MX_PATH}/ecj.jar
          wget http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O ${JDT}
        fi
      fi
  - |
      JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz
      wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/openjdk-8u${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}-linux-amd64.tar.gz -O ${JDK_TAR}
      tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR}
      export JAVA8_HOME=${TRAVIS_BUILD_DIR}/../openjdk1.8.0_${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}
      if [ "${JDK}" == "jdk8" ]
      then
        export EXTRA_JAVA_HOMES=${JAVA_HOME} # JAVA_HOME is pointing to JDK11, which should be in EXTRA_JAVA_HOMES
        export JAVA_HOME=${JAVA8_HOME} # JAVA_HOME should point to JDK8
      fi
      if [ "${JDK}" == "jdk11" ]
      then
        export EXTRA_JAVA_HOMES=${JAVA8_HOME} # JDK8 must be placed in EXTRA_JAVA_HOME
      fi

script:
  - echo ${JAVA_HOME}
  - ${JAVA_HOME}/bin/java -version
  - mx -v --primary-suite-path ${TRAVIS_BUILD_DIR}/compiler --java-home=${JAVA_HOME} gate --strict-mode --tags ${GATE}
after_failure:
  - cat hs_err*
